name: Build Wheel on Linux

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential wget m4 xz-utils make cmake libomp-dev libeigen3-dev

      - name: Build wheel
        run: |
          ./build.sh

      - name: Test the package
        run: |
          ./test.sh

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v3
        with:
          name: wheel-amd64-linux
          path: dist/*.whl
