name: Build Wheel on Linux

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential wget cmake libomp-dev
          sudo apt-get install -y libeigen3-dev

      - name: Build wheel
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install build wheel setuptools
          python setup.py bdist_wheel --plat-name=linux_x86_64

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v3
        with:
          name: wheel
          path: dist/*.whl

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download wheel artifact
        uses: actions/download-artifact@v3
        with:
          name: wheel
          path: dist

      - name: Test the package
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install dist/*.whl
          # Add your test commands here
