name: Build Wheel on macOS

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          brew install make wget cmake
          brew install libomp
          brew install eigen

      - name: Build wheel
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install build wheel setuptools
          python setup.py bdist_wheel

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v3
        with:
          name: wheel
          path: dist/*.whl

  test:
    needs: build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download wheel artifact
        uses: actions/download-artifact@v3
        with:
          name: wheel
          path: dist

      - name: Test the package
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install dist/*.whl
          python ./tests.py
