name: Build Wheel on macOS

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          brew install make wget cmake
          brew install libomp
          brew install eigen

      - name: Build wheel
        run: |
          ./build.sh

      - name: Test the package
        run: |
          ./test.sh

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v4
        with:
          name: wheel-arm64-macos
          path: dist/*.whl
