name: Build Wheel on macOS

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          brew install make wget cmake
          brew install libomp

      - name: Build flatter
        run: make all
